# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: brokerDealer.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'brokerDealer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62rokerDealer.proto\x12\x0cstone.broker\"^\n\rWorkerCommand\x12\x35\n\x0c\x63ommand_type\x18\x01 \x01(\x0e\x32\x1f.stone.broker.WorkerCommandType\x12\x16\n\x0eimage_location\x18\x02 \x01(\x04\"\x93\x02\n\rWorkerMessage\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x35\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\x1f.stone.broker.WorkerMessageType\x12\"\n\x15image_result_location\x18\x03 \x01(\x04H\x00\x88\x01\x01\x12\x18\n\x10rock_percentages\x18\x04 \x03(\x02\x12\x0e\n\x06weight\x18\x05 \x03(\x02\x12 \n\x13image_save_location\x18\x06 \x01(\x04H\x01\x88\x01\x01\x12\x16\n\x0eimage_location\x18\x07 \x01(\x04\x42\x18\n\x16_image_result_locationB\x16\n\x14_image_save_location*[\n\x11WorkerCommandType\x12#\n\x1fWORKER_COMMAND_TYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07PROCESS\x10\x01\x12\x14\n\x10PROCESS_AND_SAVE\x10\x02*q\n\x11WorkerMessageType\x12#\n\x1fWORKER_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12\t\n\x05READY\x10\x01\x12\x0b\n\x07REQUEST\x10\x02\x12\n\n\x06RESULT\x10\x03\x12\x13\n\x0fRESULT_AND_SAVE\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'brokerDealer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WORKERCOMMANDTYPE']._serialized_start=410
  _globals['_WORKERCOMMANDTYPE']._serialized_end=501
  _globals['_WORKERMESSAGETYPE']._serialized_start=503
  _globals['_WORKERMESSAGETYPE']._serialized_end=616
  _globals['_WORKERCOMMAND']._serialized_start=36
  _globals['_WORKERCOMMAND']._serialized_end=130
  _globals['_WORKERMESSAGE']._serialized_start=133
  _globals['_WORKERMESSAGE']._serialized_end=408
# @@protoc_insertion_point(module_scope)
