// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: brokerDealer.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stone.Broker {

  /// <summary>Holder for reflection information generated from brokerDealer.proto</summary>
  public static partial class BrokerDealerReflection {

    #region Descriptor
    /// <summary>File descriptor for brokerDealer.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BrokerDealerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJicm9rZXJEZWFsZXIucHJvdG8SDHN0b25lLmJyb2tlciJeCg1Xb3JrZXJD",
            "b21tYW5kEjUKDGNvbW1hbmRfdHlwZRgBIAEoDjIfLnN0b25lLmJyb2tlci5X",
            "b3JrZXJDb21tYW5kVHlwZRIWCg5pbWFnZV9sb2NhdGlvbhgCIAEoBCKTAgoN",
            "V29ya2VyTWVzc2FnZRIRCgl3b3JrZXJfaWQYASABKAkSNQoMbWVzc2FnZV90",
            "eXBlGAIgASgOMh8uc3RvbmUuYnJva2VyLldvcmtlck1lc3NhZ2VUeXBlEiIK",
            "FWltYWdlX3Jlc3VsdF9sb2NhdGlvbhgDIAEoBEgAiAEBEhgKEHJvY2tfcGVy",
            "Y2VudGFnZXMYBCADKAISDgoGd2VpZ2h0GAUgAygCEiAKE2ltYWdlX3NhdmVf",
            "bG9jYXRpb24YBiABKARIAYgBARIWCg5pbWFnZV9sb2NhdGlvbhgHIAEoBEIY",
            "ChZfaW1hZ2VfcmVzdWx0X2xvY2F0aW9uQhYKFF9pbWFnZV9zYXZlX2xvY2F0",
            "aW9uKlsKEVdvcmtlckNvbW1hbmRUeXBlEiMKH1dPUktFUl9DT01NQU5EX1RZ",
            "UEVfVU5TUEVDSUZJRUQQABILCgdQUk9DRVNTEAESFAoQUFJPQ0VTU19BTkRf",
            "U0FWRRACKnEKEVdvcmtlck1lc3NhZ2VUeXBlEiMKH1dPUktFUl9NRVNTQUdF",
            "X1RZUEVfVU5TUEVDSUZJRUQQABIJCgVSRUFEWRABEgsKB1JFUVVFU1QQAhIK",
            "CgZSRVNVTFQQAxITCg9SRVNVTFRfQU5EX1NBVkUQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Stone.Broker.WorkerCommandType), typeof(global::Stone.Broker.WorkerMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Stone.Broker.WorkerCommand), global::Stone.Broker.WorkerCommand.Parser, new[]{ "CommandType", "ImageLocation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stone.Broker.WorkerMessage), global::Stone.Broker.WorkerMessage.Parser, new[]{ "WorkerId", "MessageType", "ImageResultLocation", "RockPercentages", "Weight", "ImageSaveLocation", "ImageLocation" }, new[]{ "ImageResultLocation", "ImageSaveLocation" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Commands sent by the broker router to a worker. image_location is a byte
  /// offset into the named input MMF passed to the worker at startup.
  /// </summary>
  public enum WorkerCommandType {
    [pbr::OriginalName("WORKER_COMMAND_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("PROCESS")] Process = 1,
    [pbr::OriginalName("PROCESS_AND_SAVE")] ProcessAndSave = 2,
  }

  /// <summary>
  /// Messages sent by a worker back to the broker router.
  /// </summary>
  public enum WorkerMessageType {
    [pbr::OriginalName("WORKER_MESSAGE_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("READY")] Ready = 1,
    [pbr::OriginalName("REQUEST")] Request = 2,
    [pbr::OriginalName("RESULT")] Result = 3,
    [pbr::OriginalName("RESULT_AND_SAVE")] ResultAndSave = 4,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorkerCommand : pb::IMessage<WorkerCommand>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkerCommand> _parser = new pb::MessageParser<WorkerCommand>(() => new WorkerCommand());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkerCommand> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stone.Broker.BrokerDealerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerCommand() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerCommand(WorkerCommand other) : this() {
      commandType_ = other.commandType_;
      imageLocation_ = other.imageLocation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerCommand Clone() {
      return new WorkerCommand(this);
    }

    /// <summary>Field number for the "command_type" field.</summary>
    public const int CommandTypeFieldNumber = 1;
    private global::Stone.Broker.WorkerCommandType commandType_ = global::Stone.Broker.WorkerCommandType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.WorkerCommandType CommandType {
      get { return commandType_; }
      set {
        commandType_ = value;
      }
    }

    /// <summary>Field number for the "image_location" field.</summary>
    public const int ImageLocationFieldNumber = 2;
    private ulong imageLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageLocation {
      get { return imageLocation_; }
      set {
        imageLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkerCommand);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkerCommand other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CommandType != other.CommandType) return false;
      if (ImageLocation != other.ImageLocation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CommandType != global::Stone.Broker.WorkerCommandType.Unspecified) hash ^= CommandType.GetHashCode();
      if (ImageLocation != 0UL) hash ^= ImageLocation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CommandType != global::Stone.Broker.WorkerCommandType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) CommandType);
      }
      if (ImageLocation != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CommandType != global::Stone.Broker.WorkerCommandType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) CommandType);
      }
      if (ImageLocation != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CommandType != global::Stone.Broker.WorkerCommandType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) CommandType);
      }
      if (ImageLocation != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageLocation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkerCommand other) {
      if (other == null) {
        return;
      }
      if (other.CommandType != global::Stone.Broker.WorkerCommandType.Unspecified) {
        CommandType = other.CommandType;
      }
      if (other.ImageLocation != 0UL) {
        ImageLocation = other.ImageLocation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CommandType = (global::Stone.Broker.WorkerCommandType) input.ReadEnum();
            break;
          }
          case 16: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CommandType = (global::Stone.Broker.WorkerCommandType) input.ReadEnum();
            break;
          }
          case 16: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WorkerMessage : pb::IMessage<WorkerMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WorkerMessage> _parser = new pb::MessageParser<WorkerMessage>(() => new WorkerMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WorkerMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stone.Broker.BrokerDealerReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerMessage(WorkerMessage other) : this() {
      _hasBits0 = other._hasBits0;
      workerId_ = other.workerId_;
      messageType_ = other.messageType_;
      imageResultLocation_ = other.imageResultLocation_;
      rockPercentages_ = other.rockPercentages_.Clone();
      weight_ = other.weight_.Clone();
      imageSaveLocation_ = other.imageSaveLocation_;
      imageLocation_ = other.imageLocation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WorkerMessage Clone() {
      return new WorkerMessage(this);
    }

    /// <summary>Field number for the "worker_id" field.</summary>
    public const int WorkerIdFieldNumber = 1;
    private string workerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkerId {
      get { return workerId_; }
      set {
        workerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 2;
    private global::Stone.Broker.WorkerMessageType messageType_ = global::Stone.Broker.WorkerMessageType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.WorkerMessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "image_result_location" field.</summary>
    public const int ImageResultLocationFieldNumber = 3;
    private readonly static ulong ImageResultLocationDefaultValue = 0UL;

    private ulong imageResultLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageResultLocation {
      get { if ((_hasBits0 & 1) != 0) { return imageResultLocation_; } else { return ImageResultLocationDefaultValue; } }
      set {
        _hasBits0 |= 1;
        imageResultLocation_ = value;
      }
    }
    /// <summary>Gets whether the "image_result_location" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasImageResultLocation {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "image_result_location" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearImageResultLocation() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "rock_percentages" field.</summary>
    public const int RockPercentagesFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_rockPercentages_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> rockPercentages_ = new pbc::RepeatedField<float>();
    /// <summary>
    /// Order: MiSang, 1x2, 2x4, 4x6, Khac.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> RockPercentages {
      get { return rockPercentages_; }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 5;
    private static readonly pb::FieldCodec<float> _repeated_weight_codec
        = pb::FieldCodec.ForFloat(42);
    private readonly pbc::RepeatedField<float> weight_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Weight {
      get { return weight_; }
    }

    /// <summary>Field number for the "image_save_location" field.</summary>
    public const int ImageSaveLocationFieldNumber = 6;
    private readonly static ulong ImageSaveLocationDefaultValue = 0UL;

    private ulong imageSaveLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageSaveLocation {
      get { if ((_hasBits0 & 2) != 0) { return imageSaveLocation_; } else { return ImageSaveLocationDefaultValue; } }
      set {
        _hasBits0 |= 2;
        imageSaveLocation_ = value;
      }
    }
    /// <summary>Gets whether the "image_save_location" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasImageSaveLocation {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "image_save_location" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearImageSaveLocation() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "image_location" field.</summary>
    public const int ImageLocationFieldNumber = 7;
    private ulong imageLocation_;
    /// <summary>
    /// Internal slot ownership correlation; this is not a processed-image path.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageLocation {
      get { return imageLocation_; }
      set {
        imageLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as WorkerMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WorkerMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorkerId != other.WorkerId) return false;
      if (MessageType != other.MessageType) return false;
      if (ImageResultLocation != other.ImageResultLocation) return false;
      if(!rockPercentages_.Equals(other.rockPercentages_)) return false;
      if(!weight_.Equals(other.weight_)) return false;
      if (ImageSaveLocation != other.ImageSaveLocation) return false;
      if (ImageLocation != other.ImageLocation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorkerId.Length != 0) hash ^= WorkerId.GetHashCode();
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) hash ^= MessageType.GetHashCode();
      if (HasImageResultLocation) hash ^= ImageResultLocation.GetHashCode();
      hash ^= rockPercentages_.GetHashCode();
      hash ^= weight_.GetHashCode();
      if (HasImageSaveLocation) hash ^= ImageSaveLocation.GetHashCode();
      if (ImageLocation != 0UL) hash ^= ImageLocation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorkerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkerId);
      }
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MessageType);
      }
      if (HasImageResultLocation) {
        output.WriteRawTag(24);
        output.WriteUInt64(ImageResultLocation);
      }
      rockPercentages_.WriteTo(output, _repeated_rockPercentages_codec);
      weight_.WriteTo(output, _repeated_weight_codec);
      if (HasImageSaveLocation) {
        output.WriteRawTag(48);
        output.WriteUInt64(ImageSaveLocation);
      }
      if (ImageLocation != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorkerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkerId);
      }
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        output.WriteRawTag(16);
        output.WriteEnum((int) MessageType);
      }
      if (HasImageResultLocation) {
        output.WriteRawTag(24);
        output.WriteUInt64(ImageResultLocation);
      }
      rockPercentages_.WriteTo(ref output, _repeated_rockPercentages_codec);
      weight_.WriteTo(ref output, _repeated_weight_codec);
      if (HasImageSaveLocation) {
        output.WriteRawTag(48);
        output.WriteUInt64(ImageSaveLocation);
      }
      if (ImageLocation != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorkerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkerId);
      }
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (HasImageResultLocation) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageResultLocation);
      }
      size += rockPercentages_.CalculateSize(_repeated_rockPercentages_codec);
      size += weight_.CalculateSize(_repeated_weight_codec);
      if (HasImageSaveLocation) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageSaveLocation);
      }
      if (ImageLocation != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageLocation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WorkerMessage other) {
      if (other == null) {
        return;
      }
      if (other.WorkerId.Length != 0) {
        WorkerId = other.WorkerId;
      }
      if (other.MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        MessageType = other.MessageType;
      }
      if (other.HasImageResultLocation) {
        ImageResultLocation = other.ImageResultLocation;
      }
      rockPercentages_.Add(other.rockPercentages_);
      weight_.Add(other.weight_);
      if (other.HasImageSaveLocation) {
        ImageSaveLocation = other.ImageSaveLocation;
      }
      if (other.ImageLocation != 0UL) {
        ImageLocation = other.ImageLocation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WorkerId = input.ReadString();
            break;
          }
          case 16: {
            MessageType = (global::Stone.Broker.WorkerMessageType) input.ReadEnum();
            break;
          }
          case 24: {
            ImageResultLocation = input.ReadUInt64();
            break;
          }
          case 34:
          case 37: {
            rockPercentages_.AddEntriesFrom(input, _repeated_rockPercentages_codec);
            break;
          }
          case 42:
          case 45: {
            weight_.AddEntriesFrom(input, _repeated_weight_codec);
            break;
          }
          case 48: {
            ImageSaveLocation = input.ReadUInt64();
            break;
          }
          case 56: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WorkerId = input.ReadString();
            break;
          }
          case 16: {
            MessageType = (global::Stone.Broker.WorkerMessageType) input.ReadEnum();
            break;
          }
          case 24: {
            ImageResultLocation = input.ReadUInt64();
            break;
          }
          case 34:
          case 37: {
            rockPercentages_.AddEntriesFrom(ref input, _repeated_rockPercentages_codec);
            break;
          }
          case 42:
          case 45: {
            weight_.AddEntriesFrom(ref input, _repeated_weight_codec);
            break;
          }
          case 48: {
            ImageSaveLocation = input.ReadUInt64();
            break;
          }
          case 56: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
