// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: brokerTx.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stone.Broker {

  /// <summary>Holder for reflection information generated from brokerTx.proto</summary>
  public static partial class BrokerTxReflection {

    #region Descriptor
    /// <summary>File descriptor for brokerTx.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BrokerTxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5icm9rZXJUeC5wcm90bxIMc3RvbmUuYnJva2VyGhJicm9rZXJEZWFsZXIu",
            "cHJvdG8igAIKDVR4UHVzaE1lc3NhZ2USNQoMbWVzc2FnZV90eXBlGAEgASgO",
            "Mh8uc3RvbmUuYnJva2VyLldvcmtlck1lc3NhZ2VUeXBlEiIKFWltYWdlX3Jl",
            "c3VsdF9sb2NhdGlvbhgCIAEoBEgAiAEBEhgKEHJvY2tfcGVyY2VudGFnZXMY",
            "AyADKAISDgoGd2VpZ2h0GAQgAygCEiAKE2ltYWdlX3NhdmVfbG9jYXRpb24Y",
            "BSABKARIAYgBARIWCg5pbWFnZV9sb2NhdGlvbhgGIAEoBEIYChZfaW1hZ2Vf",
            "cmVzdWx0X2xvY2F0aW9uQhYKFF9pbWFnZV9zYXZlX2xvY2F0aW9uYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Stone.Broker.BrokerDealerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Stone.Broker.TxPushMessage), global::Stone.Broker.TxPushMessage.Parser, new[]{ "MessageType", "ImageResultLocation", "RockPercentages", "Weight", "ImageSaveLocation", "ImageLocation" }, new[]{ "ImageResultLocation", "ImageSaveLocation" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The transmit struct is not defined yet in 2_Broker_Process. This envelope
  /// provides a stable protobuf payload for TxPathPush without assuming the
  /// eventual processed-data fields.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TxPushMessage : pb::IMessage<TxPushMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TxPushMessage> _parser = new pb::MessageParser<TxPushMessage>(() => new TxPushMessage());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TxPushMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stone.Broker.BrokerTxReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TxPushMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TxPushMessage(TxPushMessage other) : this() {
      _hasBits0 = other._hasBits0;
      messageType_ = other.messageType_;
      imageResultLocation_ = other.imageResultLocation_;
      rockPercentages_ = other.rockPercentages_.Clone();
      weight_ = other.weight_.Clone();
      imageSaveLocation_ = other.imageSaveLocation_;
      imageLocation_ = other.imageLocation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TxPushMessage Clone() {
      return new TxPushMessage(this);
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Stone.Broker.WorkerMessageType messageType_ = global::Stone.Broker.WorkerMessageType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.WorkerMessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "image_result_location" field.</summary>
    public const int ImageResultLocationFieldNumber = 2;
    private readonly static ulong ImageResultLocationDefaultValue = 0UL;

    private ulong imageResultLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageResultLocation {
      get { if ((_hasBits0 & 1) != 0) { return imageResultLocation_; } else { return ImageResultLocationDefaultValue; } }
      set {
        _hasBits0 |= 1;
        imageResultLocation_ = value;
      }
    }
    /// <summary>Gets whether the "image_result_location" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasImageResultLocation {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "image_result_location" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearImageResultLocation() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "rock_percentages" field.</summary>
    public const int RockPercentagesFieldNumber = 3;
    private static readonly pb::FieldCodec<float> _repeated_rockPercentages_codec
        = pb::FieldCodec.ForFloat(26);
    private readonly pbc::RepeatedField<float> rockPercentages_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> RockPercentages {
      get { return rockPercentages_; }
    }

    /// <summary>Field number for the "weight" field.</summary>
    public const int WeightFieldNumber = 4;
    private static readonly pb::FieldCodec<float> _repeated_weight_codec
        = pb::FieldCodec.ForFloat(34);
    private readonly pbc::RepeatedField<float> weight_ = new pbc::RepeatedField<float>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<float> Weight {
      get { return weight_; }
    }

    /// <summary>Field number for the "image_save_location" field.</summary>
    public const int ImageSaveLocationFieldNumber = 5;
    private readonly static ulong ImageSaveLocationDefaultValue = 0UL;

    private ulong imageSaveLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageSaveLocation {
      get { if ((_hasBits0 & 2) != 0) { return imageSaveLocation_; } else { return ImageSaveLocationDefaultValue; } }
      set {
        _hasBits0 |= 2;
        imageSaveLocation_ = value;
      }
    }
    /// <summary>Gets whether the "image_save_location" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasImageSaveLocation {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "image_save_location" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearImageSaveLocation() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "image_location" field.</summary>
    public const int ImageLocationFieldNumber = 6;
    private ulong imageLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageLocation {
      get { return imageLocation_; }
      set {
        imageLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TxPushMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TxPushMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (ImageResultLocation != other.ImageResultLocation) return false;
      if(!rockPercentages_.Equals(other.rockPercentages_)) return false;
      if(!weight_.Equals(other.weight_)) return false;
      if (ImageSaveLocation != other.ImageSaveLocation) return false;
      if (ImageLocation != other.ImageLocation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) hash ^= MessageType.GetHashCode();
      if (HasImageResultLocation) hash ^= ImageResultLocation.GetHashCode();
      hash ^= rockPercentages_.GetHashCode();
      hash ^= weight_.GetHashCode();
      if (HasImageSaveLocation) hash ^= ImageSaveLocation.GetHashCode();
      if (ImageLocation != 0UL) hash ^= ImageLocation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (HasImageResultLocation) {
        output.WriteRawTag(16);
        output.WriteUInt64(ImageResultLocation);
      }
      rockPercentages_.WriteTo(output, _repeated_rockPercentages_codec);
      weight_.WriteTo(output, _repeated_weight_codec);
      if (HasImageSaveLocation) {
        output.WriteRawTag(40);
        output.WriteUInt64(ImageSaveLocation);
      }
      if (ImageLocation != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (HasImageResultLocation) {
        output.WriteRawTag(16);
        output.WriteUInt64(ImageResultLocation);
      }
      rockPercentages_.WriteTo(ref output, _repeated_rockPercentages_codec);
      weight_.WriteTo(ref output, _repeated_weight_codec);
      if (HasImageSaveLocation) {
        output.WriteRawTag(40);
        output.WriteUInt64(ImageSaveLocation);
      }
      if (ImageLocation != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (HasImageResultLocation) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageResultLocation);
      }
      size += rockPercentages_.CalculateSize(_repeated_rockPercentages_codec);
      size += weight_.CalculateSize(_repeated_weight_codec);
      if (HasImageSaveLocation) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageSaveLocation);
      }
      if (ImageLocation != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageLocation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TxPushMessage other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != global::Stone.Broker.WorkerMessageType.Unspecified) {
        MessageType = other.MessageType;
      }
      if (other.HasImageResultLocation) {
        ImageResultLocation = other.ImageResultLocation;
      }
      rockPercentages_.Add(other.rockPercentages_);
      weight_.Add(other.weight_);
      if (other.HasImageSaveLocation) {
        ImageSaveLocation = other.ImageSaveLocation;
      }
      if (other.ImageLocation != 0UL) {
        ImageLocation = other.ImageLocation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Stone.Broker.WorkerMessageType) input.ReadEnum();
            break;
          }
          case 16: {
            ImageResultLocation = input.ReadUInt64();
            break;
          }
          case 26:
          case 29: {
            rockPercentages_.AddEntriesFrom(input, _repeated_rockPercentages_codec);
            break;
          }
          case 34:
          case 37: {
            weight_.AddEntriesFrom(input, _repeated_weight_codec);
            break;
          }
          case 40: {
            ImageSaveLocation = input.ReadUInt64();
            break;
          }
          case 48: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageType = (global::Stone.Broker.WorkerMessageType) input.ReadEnum();
            break;
          }
          case 16: {
            ImageResultLocation = input.ReadUInt64();
            break;
          }
          case 26:
          case 29: {
            rockPercentages_.AddEntriesFrom(ref input, _repeated_rockPercentages_codec);
            break;
          }
          case 34:
          case 37: {
            weight_.AddEntriesFrom(ref input, _repeated_weight_codec);
            break;
          }
          case 40: {
            ImageSaveLocation = input.ReadUInt64();
            break;
          }
          case 48: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
