// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: brokerRx.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stone.Broker {

  /// <summary>Holder for reflection information generated from brokerRx.proto</summary>
  public static partial class BrokerRxReflection {

    #region Descriptor
    /// <summary>File descriptor for brokerRx.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BrokerRxReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5icm9rZXJSeC5wcm90bxIMc3RvbmUuYnJva2VyIiEKB1J4RnJhbWUSFgoO",
            "aW1hZ2VfbG9jYXRpb24YASABKAQiswEKDVJ4UHVsbE1lc3NhZ2USNQoMbWVz",
            "c2FnZV90eXBlGAEgASgOMh8uc3RvbmUuYnJva2VyLlJ4UHVsbE1lc3NhZ2VU",
            "eXBlEhgKC21lc3NhZ2VfbG9nGAIgASgJSACIAQESMAoMZGF0YV9wYXlsb2Fk",
            "GAMgASgLMhUuc3RvbmUuYnJva2VyLlJ4RnJhbWVIAYgBAUIOCgxfbWVzc2Fn",
            "ZV9sb2dCDwoNX2RhdGFfcGF5bG9hZCpUChFSeFB1bGxNZXNzYWdlVHlwZRIk",
            "CiBSWF9QVUxMX01FU1NBR0VfVFlQRV9VTlNQRUNJRklFRBAAEgsKB1NUQVJU",
            "VVAQARIMCghSQVdJTUFHRRACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Stone.Broker.RxPullMessageType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Stone.Broker.RxFrame), global::Stone.Broker.RxFrame.Parser, new[]{ "ImageLocation" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Stone.Broker.RxPullMessage), global::Stone.Broker.RxPullMessage.Parser, new[]{ "MessageType", "MessageLog", "DataPayload" }, new[]{ "MessageLog", "DataPayload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RxPullMessageType {
    [pbr::OriginalName("RX_PULL_MESSAGE_TYPE_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("STARTUP")] Startup = 1,
    [pbr::OriginalName("RAWIMAGE")] Rawimage = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RxFrame : pb::IMessage<RxFrame>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RxFrame> _parser = new pb::MessageParser<RxFrame>(() => new RxFrame());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RxFrame> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stone.Broker.BrokerRxReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RxFrame() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RxFrame(RxFrame other) : this() {
      imageLocation_ = other.imageLocation_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RxFrame Clone() {
      return new RxFrame(this);
    }

    /// <summary>Field number for the "image_location" field.</summary>
    public const int ImageLocationFieldNumber = 1;
    private ulong imageLocation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong ImageLocation {
      get { return imageLocation_; }
      set {
        imageLocation_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RxFrame);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RxFrame other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ImageLocation != other.ImageLocation) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ImageLocation != 0UL) hash ^= ImageLocation.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ImageLocation != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ImageLocation != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(ImageLocation);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ImageLocation != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(ImageLocation);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RxFrame other) {
      if (other == null) {
        return;
      }
      if (other.ImageLocation != 0UL) {
        ImageLocation = other.ImageLocation;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ImageLocation = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class RxPullMessage : pb::IMessage<RxPullMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<RxPullMessage> _parser = new pb::MessageParser<RxPullMessage>(() => new RxPullMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<RxPullMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stone.Broker.BrokerRxReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RxPullMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RxPullMessage(RxPullMessage other) : this() {
      messageType_ = other.messageType_;
      messageLog_ = other.messageLog_;
      dataPayload_ = other.dataPayload_ != null ? other.dataPayload_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RxPullMessage Clone() {
      return new RxPullMessage(this);
    }

    /// <summary>Field number for the "message_type" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Stone.Broker.RxPullMessageType messageType_ = global::Stone.Broker.RxPullMessageType.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.RxPullMessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "message_log" field.</summary>
    public const int MessageLogFieldNumber = 2;
    private readonly static string MessageLogDefaultValue = "";

    private string messageLog_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MessageLog {
      get { return messageLog_ ?? MessageLogDefaultValue; }
      set {
        messageLog_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "message_log" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMessageLog {
      get { return messageLog_ != null; }
    }
    /// <summary>Clears the value of the "message_log" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMessageLog() {
      messageLog_ = null;
    }

    /// <summary>Field number for the "data_payload" field.</summary>
    public const int DataPayloadFieldNumber = 3;
    private global::Stone.Broker.RxFrame dataPayload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.RxFrame DataPayload {
      get { return dataPayload_; }
      set {
        dataPayload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as RxPullMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(RxPullMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (MessageLog != other.MessageLog) return false;
      if (!object.Equals(DataPayload, other.DataPayload)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != global::Stone.Broker.RxPullMessageType.Unspecified) hash ^= MessageType.GetHashCode();
      if (HasMessageLog) hash ^= MessageLog.GetHashCode();
      if (dataPayload_ != null) hash ^= DataPayload.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageType != global::Stone.Broker.RxPullMessageType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (HasMessageLog) {
        output.WriteRawTag(18);
        output.WriteString(MessageLog);
      }
      if (dataPayload_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageType != global::Stone.Broker.RxPullMessageType.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (HasMessageLog) {
        output.WriteRawTag(18);
        output.WriteString(MessageLog);
      }
      if (dataPayload_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DataPayload);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != global::Stone.Broker.RxPullMessageType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (HasMessageLog) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MessageLog);
      }
      if (dataPayload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DataPayload);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(RxPullMessage other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != global::Stone.Broker.RxPullMessageType.Unspecified) {
        MessageType = other.MessageType;
      }
      if (other.HasMessageLog) {
        MessageLog = other.MessageLog;
      }
      if (other.dataPayload_ != null) {
        if (dataPayload_ == null) {
          DataPayload = new global::Stone.Broker.RxFrame();
        }
        DataPayload.MergeFrom(other.DataPayload);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Stone.Broker.RxPullMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            MessageLog = input.ReadString();
            break;
          }
          case 26: {
            if (dataPayload_ == null) {
              DataPayload = new global::Stone.Broker.RxFrame();
            }
            input.ReadMessage(DataPayload);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageType = (global::Stone.Broker.RxPullMessageType) input.ReadEnum();
            break;
          }
          case 18: {
            MessageLog = input.ReadString();
            break;
          }
          case 26: {
            if (dataPayload_ == null) {
              DataPayload = new global::Stone.Broker.RxFrame();
            }
            input.ReadMessage(DataPayload);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
