// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: brokerRouter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stone.Broker {

  /// <summary>Holder for reflection information generated from brokerRouter.proto</summary>
  public static partial class BrokerRouterReflection {

    #region Descriptor
    /// <summary>File descriptor for brokerRouter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BrokerRouterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJicm9rZXJSb3V0ZXIucHJvdG8SDHN0b25lLmJyb2tlchoSYnJva2VyRGVh",
            "bGVyLnByb3RvIpMBChNCcm9rZXJSb3V0ZXJNZXNzYWdlEhEKCXdvcmtlcl9p",
            "ZBgBIAEoCRIuCgdjb21tYW5kGAIgASgLMhsuc3RvbmUuYnJva2VyLldvcmtl",
            "ckNvbW1hbmRIABIuCgdtZXNzYWdlGAMgASgLMhsuc3RvbmUuYnJva2VyLldv",
            "cmtlck1lc3NhZ2VIAEIJCgdwYXlsb2FkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Stone.Broker.BrokerDealerReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Stone.Broker.BrokerRouterMessage), global::Stone.Broker.BrokerRouterMessage.Parser, new[]{ "WorkerId", "Command", "Message" }, new[]{ "Payload" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// The ROUTER socket carries either a command to a worker or a message from
  /// a worker. The worker identity is kept separately in the ZeroMQ routing
  /// frame, but is included here for transports that carry one payload.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BrokerRouterMessage : pb::IMessage<BrokerRouterMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BrokerRouterMessage> _parser = new pb::MessageParser<BrokerRouterMessage>(() => new BrokerRouterMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BrokerRouterMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Stone.Broker.BrokerRouterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrokerRouterMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrokerRouterMessage(BrokerRouterMessage other) : this() {
      workerId_ = other.workerId_;
      switch (other.PayloadCase) {
        case PayloadOneofCase.Command:
          Command = other.Command.Clone();
          break;
        case PayloadOneofCase.Message:
          Message = other.Message.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BrokerRouterMessage Clone() {
      return new BrokerRouterMessage(this);
    }

    /// <summary>Field number for the "worker_id" field.</summary>
    public const int WorkerIdFieldNumber = 1;
    private string workerId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string WorkerId {
      get { return workerId_; }
      set {
        workerId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "command" field.</summary>
    public const int CommandFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.WorkerCommand Command {
      get { return payloadCase_ == PayloadOneofCase.Command ? (global::Stone.Broker.WorkerCommand) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Command;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Stone.Broker.WorkerMessage Message {
      get { return payloadCase_ == PayloadOneofCase.Message ? (global::Stone.Broker.WorkerMessage) payload_ : null; }
      set {
        payload_ = value;
        payloadCase_ = value == null ? PayloadOneofCase.None : PayloadOneofCase.Message;
      }
    }

    private object payload_;
    /// <summary>Enum of possible cases for the "payload" oneof.</summary>
    public enum PayloadOneofCase {
      None = 0,
      Command = 2,
      Message = 3,
    }
    private PayloadOneofCase payloadCase_ = PayloadOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PayloadOneofCase PayloadCase {
      get { return payloadCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPayload() {
      payloadCase_ = PayloadOneofCase.None;
      payload_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as BrokerRouterMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BrokerRouterMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WorkerId != other.WorkerId) return false;
      if (!object.Equals(Command, other.Command)) return false;
      if (!object.Equals(Message, other.Message)) return false;
      if (PayloadCase != other.PayloadCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (WorkerId.Length != 0) hash ^= WorkerId.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Command) hash ^= Command.GetHashCode();
      if (payloadCase_ == PayloadOneofCase.Message) hash ^= Message.GetHashCode();
      hash ^= (int) payloadCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WorkerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkerId);
      }
      if (payloadCase_ == PayloadOneofCase.Command) {
        output.WriteRawTag(18);
        output.WriteMessage(Command);
      }
      if (payloadCase_ == PayloadOneofCase.Message) {
        output.WriteRawTag(26);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WorkerId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(WorkerId);
      }
      if (payloadCase_ == PayloadOneofCase.Command) {
        output.WriteRawTag(18);
        output.WriteMessage(Command);
      }
      if (payloadCase_ == PayloadOneofCase.Message) {
        output.WriteRawTag(26);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (WorkerId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(WorkerId);
      }
      if (payloadCase_ == PayloadOneofCase.Command) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Command);
      }
      if (payloadCase_ == PayloadOneofCase.Message) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BrokerRouterMessage other) {
      if (other == null) {
        return;
      }
      if (other.WorkerId.Length != 0) {
        WorkerId = other.WorkerId;
      }
      switch (other.PayloadCase) {
        case PayloadOneofCase.Command:
          if (Command == null) {
            Command = new global::Stone.Broker.WorkerCommand();
          }
          Command.MergeFrom(other.Command);
          break;
        case PayloadOneofCase.Message:
          if (Message == null) {
            Message = new global::Stone.Broker.WorkerMessage();
          }
          Message.MergeFrom(other.Message);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            WorkerId = input.ReadString();
            break;
          }
          case 18: {
            global::Stone.Broker.WorkerCommand subBuilder = new global::Stone.Broker.WorkerCommand();
            if (payloadCase_ == PayloadOneofCase.Command) {
              subBuilder.MergeFrom(Command);
            }
            input.ReadMessage(subBuilder);
            Command = subBuilder;
            break;
          }
          case 26: {
            global::Stone.Broker.WorkerMessage subBuilder = new global::Stone.Broker.WorkerMessage();
            if (payloadCase_ == PayloadOneofCase.Message) {
              subBuilder.MergeFrom(Message);
            }
            input.ReadMessage(subBuilder);
            Message = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            WorkerId = input.ReadString();
            break;
          }
          case 18: {
            global::Stone.Broker.WorkerCommand subBuilder = new global::Stone.Broker.WorkerCommand();
            if (payloadCase_ == PayloadOneofCase.Command) {
              subBuilder.MergeFrom(Command);
            }
            input.ReadMessage(subBuilder);
            Command = subBuilder;
            break;
          }
          case 26: {
            global::Stone.Broker.WorkerMessage subBuilder = new global::Stone.Broker.WorkerMessage();
            if (payloadCase_ == PayloadOneofCase.Message) {
              subBuilder.MergeFrom(Message);
            }
            input.ReadMessage(subBuilder);
            Message = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
